<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<wsdl:definitions xmlns="http://tempuri.org/Customer_MsgSet" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://tempuri.org/Customer_MsgSet" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="Customer_MsgSet" targetNamespace="http://tempuri.org/Customer_MsgSet">
  <wsdl:documentation>
    <wsdl:appinfo source="WMQI_APPINFO">
      <MRWSDLAppInfo imported="true">
        <generatedXSD location="Customer_MsgSetService_InlineSchema1.xsd"/>
        <binding hasEncoding="false" imported="true" name="Customer_MsgSetSOAP_HTTP_Binding" originalBindingStyle="document"/>
      </MRWSDLAppInfo>
    </wsdl:appinfo>
  </wsdl:documentation>
    
  <wsdl:types>
        
          
    <xsd:schema xmlns:ibmSchExtn="http://www.ibm.com/schema/extensions" xmlns:mrm="http://tempuri.org/Customer_MsgSet" targetNamespace="http://tempuri.org/Customer_MsgSet">
      
      <xsd:include schemaLocation="Customer_MsgSetService_InlineSchema1.xsd"/>
    </xsd:schema>
        
  </wsdl:types>
    
  <wsdl:message name="Operation1_in">
        
    <wsdl:part element="GetBalanceRequest" name="GetBalanceRequest"/>
      
  </wsdl:message>
    
  <wsdl:message name="Operation1_out">
        
    <wsdl:part element="GetBalanceResponse" name="GetBalanceResponse"/>
      
  </wsdl:message>
    
  <wsdl:message name="Operation1_fault1">
        
    <wsdl:part element="Fault" name="Fault"/>
      
  </wsdl:message>
    
  <wsdl:portType name="Customer_MsgSetPortType">
        
    <wsdl:operation name="Operation1">
            
      <wsdl:input message="Operation1_in" name="Operation1_Input"/>
            
      <wsdl:output message="Operation1_out" name="Operation1_Output"/>
            
      <wsdl:fault message="Operation1_fault1" name="Operation1_Fault"/>
          
    </wsdl:operation>
      
  </wsdl:portType>
    
  <wsdl:binding name="Customer_MsgSetSOAP_HTTP_Binding" type="Customer_MsgSetPortType">
        
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        
    <wsdl:operation name="Operation1">
            
      <soap:operation soapAction=""/>
            
      <wsdl:input name="Operation1_Input">
                
        <soap:body parts="GetBalanceRequest" use="literal"/>
              
      </wsdl:input>
            
      <wsdl:output name="Operation1_Output">
                
        <soap:body parts="GetBalanceResponse" use="literal"/>
              
      </wsdl:output>
            
      <wsdl:fault name="Operation1_Fault">
                
        <soap:fault name="Operation1_Fault" use="literal"/>
              
      </wsdl:fault>
          
    </wsdl:operation>
      
  </wsdl:binding>
    
  <wsdl:service name="CustomerService">
        
    <wsdl:port binding="Customer_MsgSetSOAP_HTTP_Binding" name="CustomerService">
            
      <soap:address location="http://localhost:7800/CustomerService"/>
          
    </wsdl:port>
      
  </wsdl:service>
  
</wsdl:definitions>
